import type { AppSettings, Client, Order, Product, Route, Unit } from "./types";

export const units: Unit[] = [
  "caixa",
  "unidade",
  "maço",
  "bandeja",
  "dúzia",
  "cartela",
  "saco",
  "pacote",
];

export const initialRoutes: Route[] = [{ id: "route-principal", nome: "Rota Principal", ativo: true }];

export const initialSettings: AppSettings = {
  appName: "HortiGiro",
  companyName: "Rian Hortifruti",
  primaryColor: "#287e1d",
  pdfFooter: "Gerado pelo HortiGiro",
  logoDataUrl: "",
  telefone: "",
  cidade: "",
  cnpj: "",
};

export const initialClients: Client[] = [];

export const initialProducts: Product[] = [];

export const suggestedProducts: Product[] = [
  { id: "catalogo-1", nome: "Repolho", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-2", nome: "Couve-flor", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-3", nome: "Alface", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-4", nome: "Ovos", unidadePadrao: "cartela", ativo: true },
  { id: "catalogo-5", nome: "Alface americana", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-6", nome: "Alface roxa", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-7", nome: "Cheiro-verde", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-8", nome: "Salsinha", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-9", nome: "Rúcula", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-10", nome: "Agrião", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-11", nome: "Radite", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-12", nome: "Brócolis", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-13", nome: "Acelga", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-14", nome: "Couve-manteiga", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-15", nome: "Rabanete", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-16", nome: "Nabo", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-17", nome: "Broto feijão", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-18", nome: "Broto alfafa", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-19", nome: "Cambuci", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-20", nome: "Quiabo", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-21", nome: "Batata Monalisa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-22", nome: "Batata fritura", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-23", nome: "Batata conserva", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-24", nome: "Cebola", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-25", nome: "Cebola conserva", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-26", nome: "Tomate", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-27", nome: "Tomate cereja", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-28", nome: "Pepino", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-29", nome: "Pepino conserva", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-30", nome: "Pimentão", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-31", nome: "Pimentão misto", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-32", nome: "Vagem", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-33", nome: "Chuchu", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-34", nome: "Batata doce", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-35", nome: "Berinjela", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-36", nome: "Cenoura", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-37", nome: "Beterraba", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-38", nome: "Mandioca", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-39", nome: "Abobrinha verde", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-40", nome: "Abobrinha seca", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-41", nome: "Abóbora moranga", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-42", nome: "Laranja 20 kg", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-43", nome: "Abóbora cabotiá", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-44", nome: "Limão", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-45", nome: "Abacaxi T8", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-46", nome: "Abacaxi T12", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-47", nome: "Banana", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-48", nome: "Banana prata", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-49", nome: "Maçã", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-50", nome: "Mamão", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-51", nome: "Melão", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-52", nome: "Manga", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-53", nome: "Melancia", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-54", nome: "Alho", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-55", nome: "Feijão", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-56", nome: "Ponkan", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-57", nome: "Uva", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-58", nome: "Morango", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-59", nome: "Batata salsa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-60", nome: "Almeirão", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-61", nome: "Chicória", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-62", nome: "Escarola", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-63", nome: "Espinafre", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-64", nome: "Mostarda", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-65", nome: "Hortelã", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-66", nome: "Manjericão", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-67", nome: "Cebolinha", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-68", nome: "Alho-poró", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-69", nome: "Mexerica", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-70", nome: "Kiwi", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-71", nome: "Pera", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-72", nome: "Ameixa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-73", nome: "Pêssego", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-74", nome: "Nectarina", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-75", nome: "Caqui", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-76", nome: "Goiaba", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-77", nome: "Maracujá", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-78", nome: "Pitaya", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-79", nome: "Coco verde", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-80", nome: "Pimenta dedo-de-moça", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-81", nome: "Pimenta biquinho", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-82", nome: "Louro", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-83", nome: "Alecrim", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-84", nome: "Tomilho", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-85", nome: "Milho verde", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-86", nome: "Coco seco", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-87", nome: "Amendoim", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-88", nome: "Mandioca descascada", unidadePadrao: "pacote", ativo: true },
  { id: "catalogo-89", nome: "Batata salsa amarela", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-90", nome: "Cogumelos", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-91", nome: "Champignon", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-92", nome: "Shimeji", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-93", nome: "Abacaxi", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-94", nome: "Abóbora", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-95", nome: "Abobrinha", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-96", nome: "Aipim", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-97", nome: "Alface crespa", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-98", nome: "Alface rubi", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-99", nome: "Batata", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-100", nome: "Batata pirulito", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-101", nome: "Chicória italiana", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-102", nome: "Feijão carioca", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-103", nome: "Feijão preto", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-104", nome: "Laranja", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-105", nome: "Limão taiti", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-106", nome: "Maçã Fuji", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-107", nome: "Pepino japonês", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-108", nome: "Pepino salada", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-109", nome: "Pimenta cambuci", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-110", nome: "Pimentão verde", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-111", nome: "Repolho roxo", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-112", nome: "Salsão", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-113", nome: "Tomate salada", unidadePadrao: "caixa", ativo: true },
];

export const initialOrders: Order[] = [];
