import type { AppSettings, Client, Order, Product, Route, Unit } from "./types";

export const units: Unit[] = [
  "caixa",
  "caixa com 12 un",
  "unidade",
  "maço",
  "bandeja",
  "dúzia",
  "cartela",
  "saco",
  "pacote",
  "kg",
];

export const initialRoutes: Route[] = [{ id: "route-principal", nome: "Rota Principal", ativo: true }];

export const initialSettings: AppSettings = {
  appName: "HortiGiro",
  companyName: "Rian Hortifruti",
  primaryColor: "#287e1d",
  pdfFooter: "Gerado pelo HortiGiro",
  logoDataUrl: "",
  telefone: "",
  cidade: "",
  cnpj: "",
};

export const initialClients: Client[] = [];

export const initialProducts: Product[] = [];

export const suggestedProducts: Product[] = [
  { id: "catalogo-1", nome: "Abacaxi Havaí T8", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-2", nome: "Abacaxi Havaí T10", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-3", nome: "Abacaxi Havaí T12", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-4", nome: "Abacaxi Havaí T15", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-5", nome: "Abacaxi Pérola T8", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-6", nome: "Abacaxi Pérola T10", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-7", nome: "Abacaxi Pérola T12", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-8", nome: "Abacaxi Pérola T15", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-9", nome: "Abacaxi Pérola T18", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-10", nome: "Abóbora pescoço", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-11", nome: "Abóbora cabotiá", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-12", nome: "Abóbora moranga", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-13", nome: "Abobrinha seca", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-14", nome: "Abobrinha verde", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-15", nome: "Acelga caixa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-16", nome: "Acelga unidade", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-17", nome: "Agrião", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-18", nome: "Aipim", unidadePadrao: "kg", ativo: true },
  { id: "catalogo-19", nome: "Alface americana", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-20", nome: "Alface crespa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-21", nome: "Alface lisa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-22", nome: "Alface roxa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-23", nome: "Alface rubi", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-24", nome: "Alho", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-25", nome: "Alho descascado", unidadePadrao: "kg", ativo: true },
  { id: "catalogo-26", nome: "Alho-poró", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-27", nome: "Alecrim", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-28", nome: "Almeirão", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-29", nome: "Amendoim", unidadePadrao: "kg", ativo: true },
  { id: "catalogo-30", nome: "Ameixa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-31", nome: "Banana", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-32", nome: "Banana prata", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-33", nome: "Batata 25kg", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-34", nome: "Batata conserva", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-35", nome: "Batata diversa", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-36", nome: "Batata doce", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-37", nome: "Batata fritura", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-38", nome: "Batata Monalisa Top", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-39", nome: "Batata pirulito", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-40", nome: "Batata salsa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-41", nome: "Berinjela", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-42", nome: "Beterraba", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-43", nome: "Brócolis", unidadePadrao: "caixa com 12 un", ativo: true },
  { id: "catalogo-44", nome: "Broto alfafa", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-45", nome: "Broto feijão", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-46", nome: "Cambuci", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-47", nome: "Caqui", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-48", nome: "Cebola conserva", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-49", nome: "Cebola CX3", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-50", nome: "Cebola diversa", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-51", nome: "Cebolinha", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-52", nome: "Cenoura", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-53", nome: "Champignon", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-54", nome: "Cheiro-verde", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-55", nome: "Chicória", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-56", nome: "Chicória italiana", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-57", nome: "Chuchu", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-58", nome: "Coco seco", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-59", nome: "Coco verde", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-60", nome: "Cogumelos", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-61", nome: "Couve-flor", unidadePadrao: "caixa com 12 un", ativo: true },
  { id: "catalogo-62", nome: "Couve-manteiga", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-63", nome: "Escarola", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-64", nome: "Espinafre", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-65", nome: "Feijão carioca 30kg", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-66", nome: "Feijão preto 30kg", unidadePadrao: "saco", ativo: true },
  { id: "catalogo-67", nome: "Goiaba", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-68", nome: "Hortelã", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-69", nome: "Kiwi", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-70", nome: "Laranja 18kg", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-71", nome: "Laranja 20kg", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-72", nome: "Laranja Bahia", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-73", nome: "Limão siciliano", unidadePadrao: "kg", ativo: true },
  { id: "catalogo-74", nome: "Limão taiti", unidadePadrao: "kg", ativo: true },
  { id: "catalogo-75", nome: "Louro", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-76", nome: "Maçã", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-77", nome: "Maçã Fuji", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-78", nome: "Maçã sacolão caixa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-79", nome: "Maçã sacolão kg", unidadePadrao: "kg", ativo: true },
  { id: "catalogo-80", nome: "Mamão caixa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-148", nome: "Mamão unidade", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-81", nome: "Mandioca descascada", unidadePadrao: "kg", ativo: true },
  { id: "catalogo-82", nome: "Mandioca suja", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-83", nome: "Manga caixa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-84", nome: "Manga kg", unidadePadrao: "kg", ativo: true },
  { id: "catalogo-85", nome: "Manga Palmer", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-86", nome: "Manjericão", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-87", nome: "Maracujá caixa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-88", nome: "Maracujá kg", unidadePadrao: "kg", ativo: true },
  { id: "catalogo-89", nome: "Melancia", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-90", nome: "Melão caixa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-91", nome: "Melão unidade", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-92", nome: "Mexerica", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-93", nome: "Milho verde", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-94", nome: "Morango", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-95", nome: "Mostarda", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-96", nome: "Nabo", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-97", nome: "Nectarina", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-98", nome: "Ovos encartelados", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-99", nome: "Ovos soltos", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-100", nome: "Pepino", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-101", nome: "Pepino conserva", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-102", nome: "Pepino japonês", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-103", nome: "Pera", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-104", nome: "Pêssego", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-105", nome: "Pimenta biquinho", unidadePadrao: "kg", ativo: true },
  { id: "catalogo-106", nome: "Pimenta cambuci", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-107", nome: "Pimenta dedo-de-moça", unidadePadrao: "kg", ativo: true },
  { id: "catalogo-108", nome: "Pimentão amarelo", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-109", nome: "Pimentão misto", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-110", nome: "Pimentão verde", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-111", nome: "Pimentão vermelho", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-112", nome: "Pitaya", unidadePadrao: "kg", ativo: true },
  { id: "catalogo-113", nome: "Ponkan", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-114", nome: "Quiabo", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-115", nome: "Rabanete", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-116", nome: "Radite", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-117", nome: "Repolho caixa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-118", nome: "Repolho unidade", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-119", nome: "Repolho roxo caixa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-120", nome: "Repolho roxo unidade", unidadePadrao: "unidade", ativo: true },
  { id: "catalogo-121", nome: "Rúcula", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-122", nome: "Salsão", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-123", nome: "Salsinha", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-124", nome: "Shimeji", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-125", nome: "Tomate", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-126", nome: "Tomate cereja bandeja", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-127", nome: "Tomate cereja caixa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-128", nome: "Tomate longa vida graúdo", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-129", nome: "Tomate longa vida médio", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-130", nome: "Tomate miúdo", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-131", nome: "Tomate salada", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-132", nome: "Tomate saladete graúdo", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-133", nome: "Tomate saladete médio", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-134", nome: "Tomate saladete miúdo", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-135", nome: "Tomilho", unidadePadrao: "maço", ativo: true },
  { id: "catalogo-136", nome: "Uva", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-137", nome: "Uva benitaka", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-138", nome: "Uva brasil", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-139", nome: "Uva crimson bandeja", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-140", nome: "Uva crimson caixa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-141", nome: "Uva itália", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-142", nome: "Uva niágara", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-143", nome: "Uva rosada", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-144", nome: "Uva thompson bandeja", unidadePadrao: "bandeja", ativo: true },
  { id: "catalogo-145", nome: "Uva thompson caixa", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-146", nome: "Vagem", unidadePadrao: "caixa", ativo: true },
  { id: "catalogo-147", nome: "Vagem preta", unidadePadrao: "caixa", ativo: true },
];

export const initialOrders: Order[] = [];
